apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nodejs-k8s
spec: 
  selector:
    matchLabels:
      app: nodejs-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs-k8s
    spec:
      containers:
        - name: nodejs-k8s
          image: ctse/nodejs-k8s
          ports:
            - containerPort: 5000